# golangci-lint is a fast Go linters runner.
# https://golangci-lint.run 
#
# golangci-lint run
linters:
  enable-all: true
  disable:
    # deprecated
    - exportloopref
    
    - depguard          # unwanted, as it requires a list of packages
    - exhaustive        # too much boilerplate
    - exhaustruct       # too many values in struct literal (opinionated)
    - wrapcheck         # wrapping 3rd party errors are unnecessary (opinionated)
    - varnamelen        # doesn't allow short vars (opinionated)
    - goimports         # conflicts with gci
    - nlreturn          # opinionated
    - wsl               # opinionated
    - tagliatelle       # opinionated
